FROM ubuntu:20.10

COPY install-dependencies /

RUN ["/install-dependencies"]

RUN cd /tmp/ && git clone https://gitlab.freedesktop.org/gstreamer/gst-build.git && \
    mkdir -p /tmp/gst-build/build_dir/ && \
    cd /tmp/gst-build && \
    git checkout 1.18 && \
    meson build_dir \
            --prefix=/usr/ && \
            ninja -C /tmp/gst-build/build_dir/ install

RUN ( \
    echo 'LogLevel DEBUG2'; \
    echo 'PermitRootLogin yes'; \
    echo 'PasswordAuthentication yes'; \
    echo 'Subsystem sftp /usr/lib/openssh/sftp-server'; \
  ) > /etc/ssh/sshd_config_test_clion \
  && mkdir /run/sshd


RUN useradd -m user \
  && yes password | passwd user
# COPY ./ /webrtc_stream

# RUN pip3 install  -r /webrtc_stream/requirements.txt

# RUN cd /webrtc_stream && /usr/bin/cmake .
# RUN cd /webrtc_stream && /usr/bin/make

# this is for debugging with clion
CMD ["/usr/sbin/sshd", "-D", "-e", "-f", "/etc/ssh/sshd_config_test_clion"]
